package com.selland.persistence;

import java.util.ArrayList;
import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

@JsonSerialize
@JsonInclude(Include.NON_NULL)
@DynamoDBTable(tableName="MealTable")
public class MealSet {
    
	private String mealId;
	private String requestId;
	private String evaluationId;
	private String recorderSerialNumber;
	private List<Meal> meals = new ArrayList<Meal>();
    
    public MealSet() { }   

    @DynamoDBHashKey(attributeName="mealId")
    @DynamoDBAutoGeneratedKey
    public String getMealId() { return mealId; }
    public void setMealId(String mealId) { this.mealId = mealId; }
    
	@DynamoDBAttribute(attributeName="requestId")
    public String getRequestId() { return requestId; }
    public void setRequestId(String requestId) { this.requestId = requestId; }
    
    @DynamoDBAttribute(attributeName="evaluationId")
    public String getEvaluationId() { return evaluationId; }
    public void setEvaluationId(String evaluationId) { this.evaluationId = evaluationId; }
    
    @DynamoDBAttribute(attributeName="recorderSerialNumber")
    public String getRecorderSerialNumber() { return recorderSerialNumber; }
    public void setRecorderSerialNumber(String recorderSerialNumber) { this.recorderSerialNumber = recorderSerialNumber; }
    
    @DynamoDBAttribute(attributeName="meals")
    public List<Meal> getMeals() { return meals; }
    public void setMeals(List<Meal> meals) { this.meals = meals; }
    
}